flasher:
    default: sweetalert
    auto_translate: false
    presets:
        created:
            type: success
            title: success
            message: Data created successfully

flasher_sweetalert:
    options:
        confirmButtonColor: '#FFFF00'